disablePathToLower: true
languageCode: en-us
title: Àlex Fiestas's blog
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  top:
  - identifier: home
    name: Home
    title: Home
    pageref: "/"
    weight: -900
  - identifier: blog
    name: Blog
    title: Posts and musings
    pageref: /blog
    weight: -800
  - identifier: projects
    name: Projects
    title: List of projects
    pageref: /projects
    weight: -700
  - identifier: recipes
    name: Recipes
    title: List of recipes
    pageref: /recipes
    weight: -600
  - identifier: experience
    name: Experience
    title: Profesional experience
    pageref: /experience
    weight: -500
  social:
  - identifier: feed
    name: Feed
    title: feed
    pageref: "/"
    weight: -900
  - identifier: github
    name: Github
    title: Github
    pageref: /blog
    weight: -800
  - identifier: linkedin
    name: Linkedin
    title: Linkedin
    pageref: /projects
    weight: -700
  - identifier: twitter
    name: Twitter
    title: Twitter
    pageref: /recipes
    weight: -600
  utils:
  - identifier: colorScheme
    name: dark
    title: dark
    pageref: "/"
    weight: -900
  - identifier: search
    name: Search
    title: Search
    pageref: /blog
    weight: -800