languageCode: en-us
title: Àlex Fiestas's blog
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  mounts:
  - source: assets
    target: assets
permalinks:
  posts: /articles/:slug/
theme: plainlyColorful
outputFormats:
  RSS:
    baseName: "feed"
menu:
  primary:
  - identifier: home
    name: Home
    title: Home
    pageref: "/"
    weight: -900
  - identifier: blog
    name: Blog
    title: Posts and musings
    pageref: /posts/
    weight: -800
  - identifier: projects
    name: Projects
    title: List of projects
    pageref: /projects/
    weight: -700
  - identifier: recipes
    name: Recipes
    title: List of recipes
    pageref: /recipes/
    weight: -600
  - identifier: experience
    name: Experience
    title: Professional experience
    pageref: /experiences
    weight: -500
  secondary:
  - identifier: feed
    name: Feed
    title: feed
    pageref: "/"
    weight: -900
  - identifier: gh
    name: Github
    title: Github
    pageref: /blog
    weight: -800
  - identifier: in
    name: Linkedin
    title: Linkedin
    pageref: /projects
    weight: -700
  - identifier: birdsite
    name: Twitter
    title: Twitter
    pageref: /recipes
    weight: -600
  - identifier: darkmode
    name: dark
    title: dark
    pageref: "/"
    weight: -500
  - identifier: search
    name: Search
    title: Search
    pageref: /blog
    weight: -400