name: Àlex Fiestas's blog
title: Àlex Fiestas's blog
description: Playground for hacking
subtitle: "Hacking: Playful cleverness"
url: http://afiestas.org
markdown: redcarpet
pygments: true
permalink: /:title/
comments: true
email: afiestaso@gmail.com
cover: "assets/header_image2.jpg"
logo: "assets/logo2.png"
baseurl: "/"

sass:
  sass_dir: _sass
  style: compressed

# External gems
gems:
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site wide configuration

title:            Site Title
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Your Name
  avatar: foo.jpeg
  bio: "Describe your self.asd sa d ad a asd qwdqwdqwdw wdwdwqd qwdqwd"
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: aaaaa#username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: fff#username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Disqus comments
disqus_shortname: afiestas

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

social:
  - name: Twitter
    icon: twitter
    username: afiestas
    url: https://twitter.com/afiestas
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: afiestas
    url: https://github.com/afiestas
    desc: Fork me on GitHub
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
