name: Àlex Fiestas's blog
title: Àlex Fiestas's blog
description: Playground for hacking
subtitle: "Hacking: Playful cleverness"
url: http://afiestas.org
markdown: kramdown
highlighter: pygments
permalink: /:title/
comments: true
email: afiestaso@gmail.com
cover: "assets/header_image2.jpg"
logo: "assets/logo2.png"
baseurl: "/"

sass:
  sass_dir: _sass
  style: compressed

# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site wide configuration
locale:           en_US
permalink:   /:categories/:title/

# Build settings
paginate: 5
paginate_path: "/page:num/"
