name: build-site
on: [push]
jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Jekyll build
        run: |
          make build
      - name: Built files
        run: |
          ls -la ${{ github.workspace }}/jekyll/_site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jekyll/_site
