name: build-site
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Jekyll build
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'jekyll'
          target_branch: 'gh-pages'
      - name: Hugo build newsroom
        uses: afiestas/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          args: --gc --minify --cleanDestinationDir --theme=newsroom --config config.yaml,newsroom.yaml
          siteDir: hugo
          destinationDir: newsroom
      - name: Hugo build plainlyColorful
        uses: afiestas/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          args: --gc --minify --cleanDestinationDir --theme=plainlyColorful --config config.yaml,plainlyColorful.yaml
          siteDir: hugo
          destinationDir: plainlyColorful
