name: build-site
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Hugo build
        uses: afiestas/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          args: --gc --minify --cleanDestinationDir --theme=newsroom
          siteDir: hugo
          destination_directory: hugo
      - name: Jekyll build
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'jekyll'
          target_branch: 'gh-pages'
