name: build-site
on: [push]
jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jekyll build
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'jekyll'
          target_branch: 'gh-pages'
