name: build-site
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Hugo build
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          args: --gc --cleanDestinationDir
          siteDir: hugo
          hugoVersion: 0.113.0
